<?require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Услуги нашей компании");
$APPLICATION->SetTitle("Услуги");
$APPLICATION->SetPageProperty("keywords", "Ключевые, слова, вашей, страницы");
$APPLICATION->SetPageProperty("description", "Описание страницы");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"services",
	array(
		"OPTION_THEME" => $optionTheme,
		"ASSET" => $asset,
		"ADD_ELEMENT_CHAIN" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "services",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "DATE_ACTIVE_FROM",
			5 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "SIZE_TITLE",
			1 => "CATEGORY",
			2 => "PRICE",
			3 => "DOCUMENTS",
			4 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"IBLOCK_ID" => "#SERVICES_IBLOCK_ID#",
		"IBLOCK_TYPE" => "redcode_mcorporate",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DATE_CREATE",
			4 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "CATEGORY",
			1 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_TEMPLATE" => "redcode",
		"PAGER_TITLE" => "Услуги",
		"PREVIEW_TRUNCATE_LEN" => "180",
		"SEF_FOLDER" => "#SITE_DIR#services/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_SHARE" => "Y",
		"FILE_404" => "",
		"CATEGORY_IBLOCK" => array(
			0 => "#ARTICLES_IBLOCK_ID#",
			1 => "#NEWS_IBLOCK_ID#",
			2 => "#SHARES_IBLOCK_ID#",
			3 => "#PROJECTS_IBLOCK_ID#",
			4 => "#SERVICES_IBLOCK_ID#",
		),
		"CATEGORY_CODE" => "CATEGORY",
		"CATEGORY_ITEMS_COUNT" => "2",
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_SHORTEN_URL_KEY" => "",
		"FILTER_NAME" => "459",
		"FILTER_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"BLOCK_QUESTION" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_NAME" => "Y",
		"USE_CATEGORY" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"USE_SEARCH" => "",
		"USE_RSS" => "",
		"USE_RATING" => "",
		"USE_CATEGORIES" => "",
		"USE_REVIEW" => "",
		"USE_FILTER" => "",
		"DETAIL_DISPLAY_TOP_PAGER" => "",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "",
		"STRICT_SECTION_CHECK" => "Y",
		"DISPLAY_TOP_PAGER" => "",
		"PAGER_SHOW_ALWAYS" => "",
		"PAGER_SHOW_ALL" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>

<?require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>