
<?if(!empty($arResult['SHOW_CATALOG'])){?>

<div class="container-fluid pb-5">
	<div class="row">
			<div class="col-sm-12 pl-0 pr-0">
			<?
			if(!empty($arResult['SHOW_CATALOG']['FILTER'])){
				global $bfilter;
				$bfilter=$arResult['SHOW_CATALOG']['FILTER'];
			}
			?>
			
<?
$arpram=array (
  'ACTION_VARIABLE' => 'action',
  'ADD_ELEMENT_CHAIN' => 'Y',
  'ADD_PROPERTIES_TO_BASKET' => 'N',
  'ADD_SECTIONS_CHAIN' => 'Y',
  'AJAX_MODE' => 'N',
  'AJAX_OPTION_ADDITIONAL' => '',
  'AJAX_OPTION_HISTORY' => 'Y',
  'AJAX_OPTION_JUMP' => 'N',
  'AJAX_OPTION_STYLE' => 'Y',
  'ALSO_BUY_ELEMENT_COUNT' => '15',
  'ALSO_BUY_MIN_BUYES' => '2',
  'BASKET_URL' => '/internet_shop/basket/',
  'CACHE_FILTER' => 'Y',
  'CACHE_GROUPS' => 'Y',
  'CACHE_NOTES' => '',
  'CACHE_TIME' => '360000000',
  'CACHE_TYPE' => 'N',
  'COMPONENT_TEMPLATE' => 'ajax_new',
  'CONVERT_CURRENCY' => 'N',
  'DETAIL_BACKGROUND_IMAGE' => '-',
  'DETAIL_BROWSER_TITLE' => '-',
  'DETAIL_CHECK_SECTION_ID_VARIABLE' => 'N',
  'DETAIL_META_DESCRIPTION' => '-',
  'DETAIL_META_KEYWORDS' => '-',
  'DETAIL_PROPERTY_CODE' => 
  array (
    0 => 'BREND',
    1 => 'KALIBR',
    2 => 'STRANA',
    3 => 'DULNAYA_ENERGIYA',
    4 => 'POL',
    5 => 'TREBUETSYA_LITSENZIYA',
    6 => 'CML2_ARTICLE',
    7 => 'RAZMER',
    8 => 'CML2_BAR_CODE',
    9 => 'MATERIAL',
    10 => 'TSVET',
    11 => 'SEZON',
    12 => 'WE_RECOMEND_WITH_IT',
    13 => 'TSVET_1',
    14 => 'DIAMETR_VYKHODNOGO_ZRACHKA_MM_1',
    15 => 'MASSA_G',
    16 => 'UVELICHENIE_KRATNOST',
    17 => 'UGLOVOE_POLE_ZRENIYA',
    18 => 'DIAMETR_VYKHODNOGO_ZRACHKA_MM',
    19 => 'DIAMETR_OBEKTIVA_MM',
  ),
  'DETAIL_SET_CANONICAL_URL' => 'Y',
  'DETAIL_SET_VIEWED_IN_COMPONENT' => 'N',
  'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
  'DISPLAY_BOTTOM_PAGER' => 'Y',
  'DISPLAY_TOP_PAGER' => 'N',
  'ELEMENT_SORT_FIELD' => 'HAS_DETAIL_PICTURE',
  'ELEMENT_SORT_FIELD2' => 'PROPERTY_OLD_PRICE',
  'ELEMENT_SORT_ORDER' => 'desc,nulls',
  'ELEMENT_SORT_ORDER2' => 'desc',
  'EX_FILTER_IBLOCK_ID' => '48',
  'FILE_404' => '',
  'FILTER_FIELD_CODE' => 
  array (
    0 => 'DETAIL_TEXT',
    1 => '',
  ),
  'FILTER_NAME' => 'shopFilter',
  'FILTER_PRICE_CODE' => 
  array (
    0 => 'Розничная',
  ),
  'FILTER_PROPERTY_CODE' => 
  array (
    0 => '',
    1 => 'KOLICHESTVO6',
    2 => '',
  ),
  'GIFTS_DETAIL_BLOCK_TITLE' => 'Выберите один из подарков',
  'GIFTS_DETAIL_HIDE_BLOCK_TITLE' => 'N',
  'GIFTS_DETAIL_PAGE_ELEMENT_COUNT' => '3',
  'GIFTS_DETAIL_TEXT_LABEL_GIFT' => 'Подарок',
  'GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE' => 'Выберите один из товаров, чтобы получить подарок',
  'GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE' => 'N',
  'GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT' => '3',
  'GIFTS_MESS_BTN_BUY' => 'Выбрать',
  'GIFTS_SECTION_LIST_BLOCK_TITLE' => 'Подарки к товарам этого раздела',
  'GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE' => 'N',
  'GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT' => '3',
  'GIFTS_SECTION_LIST_TEXT_LABEL_GIFT' => 'Подарок',
  'GIFTS_SHOW_DISCOUNT_PERCENT' => 'Y',
  'GIFTS_SHOW_IMAGE' => 'Y',
  'GIFTS_SHOW_NAME' => 'Y',
  'GIFTS_SHOW_OLD_PRICE' => 'Y',
  'HIDE_NOT_AVAILABLE' => 'N',
  'IBLOCK_ID' => '40',
  'IBLOCK_TYPE' => '1c_catalog',
  'INCLUDE_SUBSECTIONS' => 'Y',
  'LINE_ELEMENT_COUNT' => '3',
  'LINK_ELEMENTS_URL' => 'link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#',
  'LINK_IBLOCK_ID' => '',
  'LINK_IBLOCK_TYPE' => '',
  'LINK_PROPERTY_SID' => '',
  'LIST_BROWSER_TITLE' => '-',
  'LIST_META_DESCRIPTION' => '-',
  'LIST_META_KEYWORDS' => '-',
  'LIST_PROPERTY_CODE' => 
  array (
    0 => 'SALE',
    1 => 'BESTPRICE',
    2 => 'NOVINKA',
    3 => 'SPECIAL_PRICE',
    4 => 'STARAYA_TSENA',
    5 => '',
  ),
  'MESSAGE_404' => '',
  'PAGER_BASE_LINK_ENABLE' => 'N',
  'PAGER_DESC_NUMBERING' => 'N',
  'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
  'PAGER_SHOW_ALL' => 'N',
  'PAGER_SHOW_ALWAYS' => 'N',
  'PAGER_TEMPLATE' => '',
  'PAGER_TITLE' => 'Товары',
  'PAGE_ELEMENT_COUNT' => '30',
  'PARTIAL_PRODUCT_PROPERTIES' => 'N',
  'PRICE_CODE' => 
  array (
    0 => 'Розничная',
  ),
  'PRICE_VAT_INCLUDE' => 'Y',
  'PRICE_VAT_SHOW_VALUE' => 'Y',
  'PRODUCT_ID_VARIABLE' => 'id',
  'PRODUCT_PROPERTIES' => 
  array (
  ),
  'PRODUCT_PROPS_VARIABLE' => 'prop',
  'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
  'SECTION_BACKGROUND_IMAGE' => '-',
  'SECTION_COUNT_ELEMENTS' => 'N',
  'SECTION_ID_VARIABLE' => 'SECTION_ID',
  'SECTION_TOP_DEPTH' => '2',
  'SEF_FOLDER' => '/internet_shop/',
  'SEF_MODE' => 'Y',
  'SET_LAST_MODIFIED' => 'N',
  'SET_STATUS_404' => 'Y',
  'SET_TITLE' => 'Y',
  'SHOW_404' => 'Y',
  'SHOW_DEACTIVATED' => 'N',
  'SHOW_PRICE_COUNT' => '1',
  'SHOW_TOP_ELEMENTS' => 'Y',
  'TOP_ELEMENT_COUNT' => '8',
  'TOP_ELEMENT_SORT_FIELD' => 'name',
  'TOP_ELEMENT_SORT_FIELD2' => 'id',
  'TOP_ELEMENT_SORT_ORDER' => 'asc',
  'TOP_ELEMENT_SORT_ORDER2' => 'desc',
  'TOP_LINE_ELEMENT_COUNT' => '3',
  'TOP_PROPERTY_CODE' => 
  array (
    0 => '',
    1 => 'KOLICHESTVO6',
    2 => '',
  ),
  'USE_ALSO_BUY' => 'Y',
  'USE_COMPARE' => 'N',
  'USE_ELEMENT_COUNTER' => 'Y',
  'USE_FILTER' => 'Y',
  'USE_GIFTS_DETAIL' => 'Y',
  'USE_GIFTS_MAIN_PR_SECTION_LIST' => 'Y',
  'USE_GIFTS_SECTION' => 'Y',
  'USE_MAIN_ELEMENT_SECTION' => 'N',
  'USE_PRICE_COUNT' => 'N',
  'USE_PRODUCT_QUANTITY' => 'N',
  'USE_REVIEW' => 'N',
  'USE_STORE' => 'N',
  'SEF_URL_TEMPLATES' => 
  array (
    'sections' => '',
    'section' => '#SECTION_CODE_PATH#/',
    'element' => '#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
    'compare' => 'compare.php?action=#ACTION_CODE#',
    'smart_filter' => '',
  ),
  'VARIABLE_ALIASES' => 
  array (
    'compare' => 
    array (
      'ACTION_CODE' => 'action',
    ),
  ),
  '~ACTION_VARIABLE' => 'action',
  '~ADD_ELEMENT_CHAIN' => 'Y',
  '~ADD_PROPERTIES_TO_BASKET' => 'N',
  '~ADD_SECTIONS_CHAIN' => 'Y',
  '~AJAX_MODE' => 'N',
  '~AJAX_OPTION_ADDITIONAL' => '',
  '~AJAX_OPTION_HISTORY' => 'Y',
  '~AJAX_OPTION_JUMP' => 'N',
  '~AJAX_OPTION_STYLE' => 'Y',
  '~ALSO_BUY_ELEMENT_COUNT' => '15',
  '~ALSO_BUY_MIN_BUYES' => '2',
  '~BASKET_URL' => '/internet_shop/basket/',
  '~CACHE_FILTER' => 'Y',
  '~CACHE_GROUPS' => 'Y',
  '~CACHE_NOTES' => '',
  '~CACHE_TIME' => '360000000',
  '~CACHE_TYPE' => 'N',
  '~COMPONENT_TEMPLATE' => 'ajax_new',
  '~CONVERT_CURRENCY' => 'N',
  '~DETAIL_BACKGROUND_IMAGE' => '-',
  '~DETAIL_BROWSER_TITLE' => '-',
  '~DETAIL_CHECK_SECTION_ID_VARIABLE' => 'N',
  '~DETAIL_META_DESCRIPTION' => '-',
  '~DETAIL_META_KEYWORDS' => '-',
  '~DETAIL_PROPERTY_CODE' => 
  array (
    0 => 'BREND',
    1 => 'KALIBR',
    2 => 'STRANA',
    3 => 'DULNAYA_ENERGIYA',
    4 => 'POL',
    5 => 'TREBUETSYA_LITSENZIYA',
    6 => 'CML2_ARTICLE',
    7 => 'RAZMER',
    8 => 'CML2_BAR_CODE',
    9 => 'MATERIAL',
    10 => 'TSVET',
    11 => 'SEZON',
    12 => 'WE_RECOMEND_WITH_IT',
    13 => 'TSVET_1',
    14 => 'DIAMETR_VYKHODNOGO_ZRACHKA_MM_1',
    15 => 'MASSA_G',
    16 => 'UVELICHENIE_KRATNOST',
    17 => 'UGLOVOE_POLE_ZRENIYA',
    18 => 'DIAMETR_VYKHODNOGO_ZRACHKA_MM',
    19 => 'DIAMETR_OBEKTIVA_MM',
  ),
  '~DETAIL_SET_CANONICAL_URL' => 'Y',
  '~DETAIL_SET_VIEWED_IN_COMPONENT' => 'N',
  '~DISABLE_INIT_JS_IN_COMPONENT' => 'N',
  '~DISPLAY_BOTTOM_PAGER' => 'Y',
  '~DISPLAY_TOP_PAGER' => 'N',
  '~ELEMENT_SORT_FIELD' => 'name',
  '~ELEMENT_SORT_FIELD2' => 'PROPERTY_NOVINKA',
  '~ELEMENT_SORT_ORDER' => 'asc',
  '~ELEMENT_SORT_ORDER2' => 'desc',
  '~EX_FILTER_IBLOCK_ID' => '48',
  '~FILE_404' => '',
  '~FILTER_FIELD_CODE' => 
  array (
    0 => 'DETAIL_TEXT',
    1 => '',
  ),
  '~FILTER_NAME' => 'shopFilter',
  '~FILTER_PRICE_CODE' => 
  array (
    0 => 'Розничная',
  ),
  '~FILTER_PROPERTY_CODE' => 
  array (
    0 => '',
    1 => 'KOLICHESTVO6',
    2 => '',
  ),
  '~GIFTS_DETAIL_BLOCK_TITLE' => 'Выберите один из подарков',
  '~GIFTS_DETAIL_HIDE_BLOCK_TITLE' => 'N',
  '~GIFTS_DETAIL_PAGE_ELEMENT_COUNT' => '3',
  '~GIFTS_DETAIL_TEXT_LABEL_GIFT' => 'Подарок',
  '~GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE' => 'Выберите один из товаров, чтобы получить подарок',
  '~GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE' => 'N',
  '~GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT' => '3',
  '~GIFTS_MESS_BTN_BUY' => 'Выбрать',
  '~GIFTS_SECTION_LIST_BLOCK_TITLE' => 'Подарки к товарам этого раздела',
  '~GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE' => 'N',
  '~GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT' => '3',
  '~GIFTS_SECTION_LIST_TEXT_LABEL_GIFT' => 'Подарок',
  '~GIFTS_SHOW_DISCOUNT_PERCENT' => 'Y',
  '~GIFTS_SHOW_IMAGE' => 'Y',
  '~GIFTS_SHOW_NAME' => 'Y',
  '~GIFTS_SHOW_OLD_PRICE' => 'Y',
  '~HIDE_NOT_AVAILABLE' => 'N',
  '~IBLOCK_ID' => '40',
  '~IBLOCK_TYPE' => '1c_catalog',
  '~INCLUDE_SUBSECTIONS' => 'Y',
  '~LINE_ELEMENT_COUNT' => '3',
  '~LINK_ELEMENTS_URL' => 'link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#',
  '~LINK_IBLOCK_ID' => '',
  '~LINK_IBLOCK_TYPE' => '',
  '~LINK_PROPERTY_SID' => '',
  '~LIST_BROWSER_TITLE' => '-',
  '~LIST_META_DESCRIPTION' => '-',
  '~LIST_META_KEYWORDS' => '-',
  '~LIST_PROPERTY_CODE' => 
  array (
    0 => 'SALE',
    1 => 'BESTPRICE',
    2 => 'NOVINKA',
    3 => 'SPECIAL_PRICE',
    4 => 'STARAYA_TSENA',
    5 => '',
  ),
  '~MESSAGE_404' => '',
  '~PAGER_BASE_LINK_ENABLE' => 'N',
  '~PAGER_DESC_NUMBERING' => 'N',
  '~PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
  '~PAGER_SHOW_ALL' => 'N',
  '~PAGER_SHOW_ALWAYS' => 'N',
  '~PAGER_TEMPLATE' => '',
  '~PAGER_TITLE' => 'Товары',
  '~PAGE_ELEMENT_COUNT' => '30',
  '~PARTIAL_PRODUCT_PROPERTIES' => 'N',
  '~PRICE_CODE' => 
  array (
    0 => 'Розничная',
  ),
  '~PRICE_VAT_INCLUDE' => 'Y',
  '~PRICE_VAT_SHOW_VALUE' => 'Y',
  '~PRODUCT_ID_VARIABLE' => 'id',
  '~PRODUCT_PROPERTIES' => 
  array (
  ),
  '~PRODUCT_PROPS_VARIABLE' => 'prop',
  '~PRODUCT_QUANTITY_VARIABLE' => 'quantity',
  '~SECTION_BACKGROUND_IMAGE' => '-',
  '~SECTION_COUNT_ELEMENTS' => 'N',
  '~SECTION_ID_VARIABLE' => 'SECTION_ID',
  '~SECTION_TOP_DEPTH' => '2',
  '~SEF_FOLDER' => '/internet_shop/',
  '~SEF_MODE' => 'Y',
  '~SET_LAST_MODIFIED' => 'N',
  '~SET_STATUS_404' => 'Y',
  '~SET_TITLE' => 'Y',
  '~SHOW_404' => 'Y',
  '~SHOW_DEACTIVATED' => 'N',
  '~SHOW_PRICE_COUNT' => '1',
  '~SHOW_TOP_ELEMENTS' => 'Y',
  '~TOP_ELEMENT_COUNT' => '8',
  '~TOP_ELEMENT_SORT_FIELD' => 'name',
  '~TOP_ELEMENT_SORT_FIELD2' => 'id',
  '~TOP_ELEMENT_SORT_ORDER' => 'asc',
  '~TOP_ELEMENT_SORT_ORDER2' => 'desc',
  '~TOP_LINE_ELEMENT_COUNT' => '3',
  '~TOP_PROPERTY_CODE' => 
  array (
    0 => '',
    1 => 'KOLICHESTVO6',
    2 => '',
  ),
  '~USE_ALSO_BUY' => 'Y',
  '~USE_COMPARE' => 'N',
  '~USE_ELEMENT_COUNTER' => 'Y',
  '~USE_FILTER' => 'Y',
  '~USE_GIFTS_DETAIL' => 'Y',
  '~USE_GIFTS_MAIN_PR_SECTION_LIST' => 'Y',
  '~USE_GIFTS_SECTION' => 'Y',
  '~USE_MAIN_ELEMENT_SECTION' => 'N',
  '~USE_PRICE_COUNT' => 'N',
  '~USE_PRODUCT_QUANTITY' => 'N',
  '~USE_REVIEW' => 'N',
  '~USE_STORE' => 'N',
  '~SEF_URL_TEMPLATES' => 
  array (
    'sections' => '',
    'section' => '#SECTION_CODE_PATH#/',
    'element' => '#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
    'compare' => 'compare.php?action=#ACTION_CODE#',
    'smart_filter' => '',
  ),
  '~VARIABLE_ALIASES' => 
  array (
    'compare' => 
    array (
      'ACTION_CODE' => 'action',
    ),
  ),
);

$APPLICATION->IncludeComponent(
				"bitrix:catalog.section", 
				"custom_cat",
				Array(
					//"CHECK_ALT_VIEW" => $CHECK_ALT_VIEW,
					"IBLOCK_TYPE" => $arpram["IBLOCK_TYPE"],
					"IBLOCK_ID" => $arpram["IBLOCK_ID"],
					"ELEMENT_SORT_FIELD" => $arpram["ELEMENT_SORT_FIELD"],
					"ELEMENT_SORT_ORDER" => $arpram["ELEMENT_SORT_ORDER"],
					"ELEMENT_SORT_FIELD2" => $arpram["ELEMENT_SORT_FIELD2"],
					"ELEMENT_SORT_ORDER2" => $arpram["ELEMENT_SORT_ORDER2"],					
					"PROPERTY_CODE" => $arpram["LIST_PROPERTY_CODE"],
					"META_KEYWORDS" => $arpram["LIST_META_KEYWORDS"],
					"META_DESCRIPTION" => $arpram["LIST_META_DESCRIPTION"],
					"BROWSER_TITLE" => $arpram["LIST_BROWSER_TITLE"],
					"INCLUDE_SUBSECTIONS" => $arpram["INCLUDE_SUBSECTIONS"],
					"BASKET_URL" => $arpram["BASKET_URL"],
					"ACTION_VARIABLE" => $arpram["ACTION_VARIABLE"],
					"PRODUCT_ID_VARIABLE" => $arpram["PRODUCT_ID_VARIABLE"],
					"SECTION_ID_VARIABLE" => $arpram["SECTION_ID_VARIABLE"],
					"PRODUCT_QUANTITY_VARIABLE" => $arpram["PRODUCT_QUANTITY_VARIABLE"],
					"FILTER_NAME" => 'bfilter',
					"CACHE_TYPE" => $arpram["CACHE_TYPE"],
					"CACHE_TIME" => $arpram["CACHE_TIME"],
					"CACHE_FILTER" => $arpram["CACHE_FILTER"],
					"CACHE_GROUPS" => $arpram["CACHE_GROUPS"],
					"SET_TITLE" => $arpram["SET_TITLE"],
					"SET_STATUS_404" => $arpram["SET_STATUS_404"],
					"DISPLAY_COMPARE" => $arpram["USE_COMPARE"],
					"PAGE_ELEMENT_COUNT" => $arpram["PAGE_ELEMENT_COUNT"],
					"LINE_ELEMENT_COUNT" => $arpram["LINE_ELEMENT_COUNT"],
					"PRICE_CODE" => $arpram["PRICE_CODE"],
					"USE_PRICE_COUNT" => $arpram["USE_PRICE_COUNT"],
					"SHOW_PRICE_COUNT" => $arpram["SHOW_PRICE_COUNT"],

					"PRICE_VAT_INCLUDE" => $arpram["PRICE_VAT_INCLUDE"],
					"USE_PRODUCT_QUANTITY" => $arpram['USE_PRODUCT_QUANTITY'],

					"DISPLAY_TOP_PAGER" => $arpram["DISPLAY_TOP_PAGER"],
					"DISPLAY_BOTTOM_PAGER" => $arpram["DISPLAY_BOTTOM_PAGER"],
					"PAGER_TITLE" => $arpram["PAGER_TITLE"],
					"PAGER_SHOW_ALWAYS" => $arpram["PAGER_SHOW_ALWAYS"],
					"PAGER_TEMPLATE" => $arpram["PAGER_TEMPLATE"],
					"PAGER_DESC_NUMBERING" => $arpram["PAGER_DESC_NUMBERING"],
					"PAGER_DESC_NUMBERING_CACHE_TIME" => $arpram["PAGER_DESC_NUMBERING_CACHE_TIME"],
					"PAGER_SHOW_ALL" => $arpram["PAGER_SHOW_ALL"],

					"OFFERS_CART_PROPERTIES" => $arpram["OFFERS_CART_PROPERTIES"],
					"OFFERS_FIELD_CODE" => $arpram["LIST_OFFERS_FIELD_CODE"],
					"OFFERS_PROPERTY_CODE" => $arpram["LIST_OFFERS_PROPERTY_CODE"],
					"OFFERS_SORT_FIELD" => $arpram["OFFERS_SORT_FIELD"],
					"OFFERS_SORT_ORDER" => $arpram["OFFERS_SORT_ORDER"],
					"OFFERS_LIMIT" => $arpram["LIST_OFFERS_LIMIT"],

					"SECTION_ID" => $sectionId,
					"SECTION_CODE" => $sectionCode,
					"SECTION_URL" => '',//$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
					"DETAIL_URL" => "",//$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
					'CONVERT_CURRENCY' => $arpram['CONVERT_CURRENCY'],
					'CURRENCY_ID' => $arpram['CURRENCY_ID'],
          			'GSetSectMetaProp' => $exGSectVarNameProp,
          			'SHOW_ALL_WO_SECTION' => 'Y' 
				),
				$component
			);
			?>	
			</div>
	</div>
</div>
<style>.sec_pages{display:none;}</style>
<?}?>