<?require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Главная страница");
$APPLICATION->SetTitle("Текстовый блок </br> для ознакомления с компанией");
$APPLICATION->SetPageProperty("keywords", "Ключевые, слова, вашего, сайта");
$APPLICATION->SetPageProperty("description", "Описание вашего сайта");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"slider",
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "slider",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"IBLOCK_ID" => "#SLIDER_IBLOCK_ID#",
		"IBLOCK_TYPE" => "redcode_mcorporate",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "",
		"PREVIEW_TRUNCATE_LEN" => "200",
		"PROPERTY_CODE" => array(
			0 => "URL",
			1 => "URL_VIDEO",
			2 => "",
		),
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "N",
		"SHOW_404" => "Y",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"FILE_404" => "",
		"CACHE_FILTER" => "N",
		"SET_BROWSER_TITLE" => "",
		"SET_META_KEYWORDS" => "",
		"SET_META_DESCRIPTION" => "",
		"SET_LAST_MODIFIED" => "",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "",
		"ADD_SECTIONS_CHAIN" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_BOTTOM_PAGER" => "",
		"PAGER_TITLE" => "",
		"SLIDER_SPEED" => "200",
		"SHOW_DOTS" => "Y",
		"MOUSE_DRAG" => "N",
		"AUTOPLAY" => "N",
		"AUTOPLAY_SPEED" => "600",
		"AUTOPLAY_HOVER_PAUSE" => "Y",
		"LOOP" => "Y",
		"ANIMATION_SLIDER" => "fadeOut",
		"SHOW_NAV" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"FILTER_NAME" => "",
		"DETAIL_URL" => "",
		"INCLUDE_SUBSECTIONS" => "",
		"STRICT_SECTION_CHECK" => "",
		"DISPLAY_TOP_PAGER" => "",
		"PAGER_DESC_NUMBERING" => "",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "",
		"PAGER_BASE_LINK_ENABLE" => "",
		"PAGER_SHOW_ALWAYS" => "N"
	),
	false
);?>

<div class="indexWrapper">
	<?$APPLICATION->IncludeComponent(
		"bitrix:news.list",
		"theses",
		array(
			"ACTIVE_DATE_FORMAT" => "d.m.Y",
			"CACHE_FILTER" => "N",
			"CACHE_GROUPS" => "Y",
			"CACHE_TIME" => "36000000",
			"CACHE_TYPE" => "A",
			"CHECK_DATES" => "Y",
			"COMPONENT_TEMPLATE" => "theses",
			"FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"HIDE_LINK_WHEN_NO_DETAIL" => "N",
			"IBLOCK_ID" => "#THESES_IBLOCK_ID#",
			"IBLOCK_TYPE" => "redcode_mcorporate",
			"MESSAGE_404" => "",
			"NEWS_COUNT" => "4",
			"PREVIEW_TRUNCATE_LEN" => "",
			"PROPERTY_CODE" => array(
				0 => "ICON",
				1 => "URL",
				2 => "",
			),
			"SET_STATUS_404" => "Y",
			"SET_TITLE" => "N",
			"SHOW_404" => "Y",
			"SORT_BY1" => "ID",
			"SORT_BY2" => "SORT",
			"SORT_ORDER1" => "ASC",
			"SORT_ORDER2" => "ASC",
			"FILE_404" => "",
			"SET_BROWSER_TITLE" => "",
			"SET_META_KEYWORDS" => "",
			"SET_META_DESCRIPTION" => "",
			"SET_LAST_MODIFIED" => "",
			"INCLUDE_IBLOCK_INTO_CHAIN" => "",
			"ADD_SECTIONS_CHAIN" => "",
			"PARENT_SECTION" => "",
			"PARENT_SECTION_CODE" => "",
			"PAGER_TEMPLATE" => "",
			"DISPLAY_BOTTOM_PAGER" => "",
			"PAGER_TITLE" => "",
			"AJAX_MODE" => "N",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "N",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_ADDITIONAL" => "",
			"FILTER_NAME" => "",
			"DETAIL_URL" => "",
			"INCLUDE_SUBSECTIONS" => "",
			"STRICT_SECTION_CHECK" => "",
			"DISPLAY_TOP_PAGER" => "",
			"PAGER_SHOW_ALWAYS" => "",
			"PAGER_DESC_NUMBERING" => "",
			"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
			"PAGER_SHOW_ALL" => "",
			"PAGER_BASE_LINK_ENABLE" => ""
		),
		false
	);?>

	<?$APPLICATION->IncludeComponent(
		"bitrix:news.list",
		"indexServices",
		array(
			"ACTIVE_DATE_FORMAT" => "",
			"CACHE_FILTER" => "N",
			"CACHE_GROUPS" => "Y",
			"CACHE_TIME" => "36000000",
			"CACHE_TYPE" => "A",
			"CHECK_DATES" => "Y",
			"COMPONENT_TEMPLATE" => "indexServices",
			"FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"HIDE_LINK_WHEN_NO_DETAIL" => "N",
			"IBLOCK_ID" => "#SERVICES_IBLOCK_ID#",
			"IBLOCK_TYPE" => "redcode_mcorporate",
			"NEWS_COUNT" => "6",
			"PREVIEW_TRUNCATE_LEN" => "",
			"PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"SET_STATUS_404" => "Y",
			"SHOW_404" => "Y",
			"SORT_BY1" => "SORT",
			"SORT_BY2" => "SORT",
			"SORT_ORDER1" => "ASC",
			"SORT_ORDER2" => "ASC",
			"FILE_404" => "",
			"INFO_LIST_TITLE" => "Предоставляемые услуги",
			"SET_TITLE" => "N",
			"SET_BROWSER_TITLE" => "",
			"SET_META_KEYWORDS" => "",
			"SET_META_DESCRIPTION" => "",
			"SET_LAST_MODIFIED" => "",
			"INCLUDE_IBLOCK_INTO_CHAIN" => "",
			"ADD_SECTIONS_CHAIN" => "",
			"PARENT_SECTION" => "",
			"PARENT_SECTION_CODE" => "",
			"PAGER_TEMPLATE" => "redcode",
			"DISPLAY_BOTTOM_PAGER" => "Y",
			"PAGER_TITLE" => "",
			"AJAX_MODE" => "N",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "N",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_ADDITIONAL" => "",
			"FILTER_NAME" => "",
			"DETAIL_URL" => "",
			"INCLUDE_SUBSECTIONS" => "",
			"STRICT_SECTION_CHECK" => "",
			"DISPLAY_TOP_PAGER" => "",
			"PAGER_DESC_NUMBERING" => "",
			"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
			"PAGER_SHOW_ALL" => "",
			"PAGER_BASE_LINK_ENABLE" => "",
			"PAGER_SHOW_ALWAYS" => "N"
		),
		false
	);?>
</div>

<div class="indexBackground">
	<?$APPLICATION->IncludeComponent(
		"bitrix:news.list",
		"indexReviews",
		array(
			"ACTIVE_DATE_FORMAT" => "",
			"CACHE_FILTER" => "N",
			"CACHE_GROUPS" => "Y",
			"CACHE_TIME" => "36000000",
			"CACHE_TYPE" => "A",
			"CHECK_DATES" => "Y",
			"COMPONENT_TEMPLATE" => "indexReviews",
			"FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"HIDE_LINK_WHEN_NO_DETAIL" => "N",
			"IBLOCK_ID" => "#REVIEWS_IBLOCK_ID#",
			"IBLOCK_TYPE" => "redcode_mcorporate",
			"MESSAGE_404" => "",
			"NEWS_COUNT" => "",
			"PREVIEW_TRUNCATE_LEN" => "",
			"PROPERTY_CODE" => array(
				0 => "",
				1 => "SERVICE",
				2 => "",
			),
			"SET_STATUS_404" => "Y",
			"SET_TITLE" => "N",
			"SHOW_404" => "Y",
			"SORT_BY1" => "ACTIVE_FROM",
			"SORT_BY2" => "SORT",
			"SORT_ORDER1" => "DESC",
			"SORT_ORDER2" => "ASC",
			"FILE_404" => "",
			"INFO_LIST_TITLE" => "Отзывы клиентов",
			"SET_BROWSER_TITLE" => "",
			"SET_META_KEYWORDS" => "",
			"SET_META_DESCRIPTION" => "",
			"SET_LAST_MODIFIED" => "",
			"INCLUDE_IBLOCK_INTO_CHAIN" => "",
			"ADD_SECTIONS_CHAIN" => "",
			"PARENT_SECTION" => "",
			"PARENT_SECTION_CODE" => "",
			"PAGER_TEMPLATE" => "redcode",
			"DISPLAY_BOTTOM_PAGER" => "Y",
			"PAGER_TITLE" => "",
			"FILTER_NAME" => "",
			"DETAIL_URL" => "",
			"AJAX_MODE" => "N",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "N",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_ADDITIONAL" => "",
			"INCLUDE_SUBSECTIONS" => "N",
			"STRICT_SECTION_CHECK" => "N",
			"DISPLAY_TOP_PAGER" => "N",
			"PAGER_SHOW_ALWAYS" => "N",
			"PAGER_DESC_NUMBERING" => "N",
			"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
			"PAGER_SHOW_ALL" => "N",
			"PAGER_BASE_LINK_ENABLE" => "N"
		),
		false
	);?>
</div>

<div class="backgroundWhite">
	<div class="indexWrapper">
		<?$APPLICATION->IncludeComponent(
			"bitrix:news.line",
			"newsFeed",
			array(
				"ACTIVE_DATE_FORMAT" => "j F Y",
				"CACHE_FILTER" => "N",
				"CACHE_GROUPS" => "Y",
				"CACHE_TIME" => "36000000",
				"CACHE_TYPE" => "A",
				"CHECK_DATES" => "Y",
				"COMPONENT_TEMPLATE" => "newsFeed",
				"FIELD_CODE" => array(
					0 => "ID",
					1 => "NAME",
					2 => "PREVIEW_PICTURE",
					3 => "DATE_ACTIVE_FROM",
					4 => "",
				),
				"HIDE_LINK_WHEN_NO_DETAIL" => "N",
				"IBLOCK_ID" => "#NEWS_IBLOCK_ID#",
				"IBLOCK_TYPE" => "redcode_mcorporate",
				"NEWS_COUNT" => "6",
				"PREVIEW_TRUNCATE_LEN" => "",
				"PROPERTY_CODE" => array(
					0 => "SHOW_IMAGE",
					1 => "PHOTO_VERTICAL",
					2 => "PHOTO_HORIZONTAL",
					3 => "",
				),
				"SET_STATUS_404" => "Y",
				"SET_TITLE" => "N",
				"SHOW_404" => "Y",
				"SORT_BY1" => "ACTIVE_FROM",
				"SORT_BY2" => "ID",
				"SORT_ORDER1" => "DESC",
				"SORT_ORDER2" => "DESC",
				"FILE_404" => "",
				"INFO_LIST_TITLE" => "Последние публикации",
				"SET_BROWSER_TITLE" => "",
				"SET_META_KEYWORDS" => "",
				"SET_META_DESCRIPTION" => "",
				"SET_LAST_MODIFIED" => "",
				"INCLUDE_IBLOCK_INTO_CHAIN" => "",
				"ADD_SECTIONS_CHAIN" => "",
				"PARENT_SECTION" => "",
				"PARENT_SECTION_CODE" => "",
				"PAGER_TEMPLATE" => "redcode",
				"DISPLAY_BOTTOM_PAGER" => "Y",
				"PAGER_TITLE" => "",
				"AJAX_MODE" => "N",
				"AJAX_OPTION_JUMP" => "N",
				"AJAX_OPTION_STYLE" => "N",
				"AJAX_OPTION_HISTORY" => "N",
				"AJAX_OPTION_ADDITIONAL" => "",
				"FILTER_NAME" => "",
				"DETAIL_URL" => "",
				"INCLUDE_SUBSECTIONS" => "",
				"STRICT_SECTION_CHECK" => "",
				"DISPLAY_TOP_PAGER" => "",
				"PAGER_DESC_NUMBERING" => "",
				"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
				"PAGER_SHOW_ALL" => "",
				"PAGER_BASE_LINK_ENABLE" => "",
				"PAGER_SHOW_ALWAYS" => "N",
				"IBLOCKS" => array(
					0 => "#NEWS_IBLOCK_ID#",
					1 => "#ARTICLES_IBLOCK_ID#",
					2 => "#SHARES_IBLOCK_ID#",
				)
			),
			false
		);?>

		<?$APPLICATION->IncludeComponent(
			"bitrix:news.list",
			"indexPartners",
			array(
				"CACHE_FILTER" => "N",
				"CACHE_GROUPS" => "Y",
				"CACHE_TIME" => "36000000",
				"CACHE_TYPE" => "A",
				"CHECK_DATES" => "Y",
				"COMPONENT_TEMPLATE" => "indexPartners",
				"FIELD_CODE" => array(
					0 => "",
					1 => "",
				),
				"IBLOCK_ID" => "#PARTNERS_IBLOCK_ID#",
				"IBLOCK_TYPE" => "redcode_mcorporate",
				"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
				"PROPERTY_CODE" => array(
					0 => "PHONE",
					1 => "EMAIL",
					2 => "",
				),
				"SET_STATUS_404" => "Y",
				"SHOW_404" => "Y",
				"SORT_BY1" => "ID",
				"SORT_BY2" => "SORT",
				"SORT_ORDER1" => "ASC",
				"SORT_ORDER2" => "ASC",
				"FILE_404" => "",
				"INFO_LIST_TITLE" => "Наши партнеры",
				"NEWS_COUNT" => "",
				"PREVIEW_TRUNCATE_LEN" => "",
				"ACTIVE_DATE_FORMAT" => "",
				"SET_TITLE" => "N",
				"SET_BROWSER_TITLE" => "",
				"SET_META_KEYWORDS" => "",
				"SET_META_DESCRIPTION" => "",
				"SET_LAST_MODIFIED" => "",
				"INCLUDE_IBLOCK_INTO_CHAIN" => "",
				"ADD_SECTIONS_CHAIN" => "",
				"HIDE_LINK_WHEN_NO_DETAIL" => "N",
				"PARENT_SECTION" => "",
				"PARENT_SECTION_CODE" => "",
				"PAGER_TEMPLATE" => "redcode",
				"DISPLAY_BOTTOM_PAGER" => "Y",
				"PAGER_TITLE" => "",
				"FILTER_NAME" => "",
				"DETAIL_URL" => "",
				"AJAX_MODE" => "N",
				"AJAX_OPTION_JUMP" => "N",
				"AJAX_OPTION_STYLE" => "N",
				"AJAX_OPTION_HISTORY" => "N",
				"AJAX_OPTION_ADDITIONAL" => "",
				"INCLUDE_SUBSECTIONS" => "N",
				"STRICT_SECTION_CHECK" => "N",
				"DISPLAY_TOP_PAGER" => "N",
				"PAGER_SHOW_ALWAYS" => "N",
				"PAGER_DESC_NUMBERING" => "N",
				"PAGER_SHOW_ALL" => "N",
				"PAGER_BASE_LINK_ENABLE" => "N"
			),
			false
		);?>
	</div>
</div>

<div class="map">
	<div class="wrapper_map">
		<div class="map_inside">
			<div class="mapContacts">
				<h2>Контакты</h2>
				<div class="contactAddress">
					<?$APPLICATION->IncludeComponent(
						"bitrix:main.include", "", 
						array(
							"AREA_FILE_SHOW" => "file",
							"PATH" => SITE_DIR."include_areas/contact/address.php",
						)
					);?>
				</div>
				<div class="contactPhone">
					<?$APPLICATION->IncludeComponent(
						"bitrix:main.include", "", 
						array(
							"AREA_FILE_SHOW" => "file",
							"PATH" => SITE_DIR."include_areas/contact/phone.php",
						)
					);?>
				</div>
				<div class="contactEmail">
					<?$APPLICATION->IncludeComponent(
						"bitrix:main.include", "", 
						array(
							"AREA_FILE_SHOW" => "file",
							"PATH" => SITE_DIR."include_areas/contact/email.php",
						)
					);?>
				</div>
			</div>
			<?$APPLICATION->IncludeComponent(
				"bitrix:main.feedback",
				"mapCallBack",
				array(
					"EMAIL_TO" => "#EMAIL#",
					"REQUIRED_FIELDS" => array(
						0 => "NAME",
						1 => "EMAIL",
					),
					"COMPONENT_TEMPLATE" => "mapCallBack",
					"EVENT_MESSAGE_ID" => "#REDCODE_WRITE_US_ID#",
					"ELEMENT_FORM" => array(
						0 => "NAME",
						1 => "SUBJECT",
						2 => "PHONE",
						3 => "EMAIL",
						4 => "MESSAGE",
					),
					"OPTION_THEME" => $optionTheme,
				),
				false
			);?>
		</div>
	</div>
	<?$APPLICATION->IncludeComponent(
		"bitrix:news.list",
		"indexContacts",
		array(
			"CACHE_FILTER" => "N",
			"CACHE_GROUPS" => "Y",
			"CACHE_TIME" => "36000000",
			"CACHE_TYPE" => "A",
			"CHECK_DATES" => "Y",
			"COMPONENT_TEMPLATE" => "indexContacts",
			"FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"FILTER_NAME" => "",
			"HIDE_LINK_WHEN_NO_DETAIL" => "N",
			"IBLOCK_ID" => "#MAP_IBLOCK_ID#",
			"IBLOCK_TYPE" => "redcode_mcorporate",
			"NEWS_COUNT" => "1",
			"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
			"PROPERTY_CODE" => array(
				0 => "MAP_COORDINATE",
				1 => "LOGO_POSITION",
				2 => "MORE_TEXT",
				3 => "",
			),
			"SET_STATUS_404" => "Y",
			"SHOW_404" => "Y",
			"SORT_BY1" => "ID",
			"SORT_BY2" => "SORT",
			"SORT_ORDER1" => "ASC",
			"SORT_ORDER2" => "ASC",
			"FILE_404" => "",
			"ZOOM_MAP" => "16",
			"SET_TITLE" => "N",
			"SET_BROWSER_TITLE" => "",
			"SET_META_KEYWORDS" => "",
			"SET_META_DESCRIPTION" => "",
			"SET_LAST_MODIFIED" => "",
			"INCLUDE_IBLOCK_INTO_CHAIN" => "",
			"ADD_SECTIONS_CHAIN" => "",
			"PARENT_SECTION" => "",
			"PARENT_SECTION_CODE" => "",
			"PAGER_TEMPLATE" => "redcode",
			"DISPLAY_BOTTOM_PAGER" => "Y",
			"PAGER_TITLE" => "",
			"PREVIEW_TRUNCATE_LEN" => "",
			"ACTIVE_DATE_FORMAT" => "",
			"DETAIL_URL" => "",
			"AJAX_MODE" => "N",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "N",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_ADDITIONAL" => "",
			"INCLUDE_SUBSECTIONS" => "N",
			"STRICT_SECTION_CHECK" => "N",
			"DISPLAY_TOP_PAGER" => "N",
			"PAGER_SHOW_ALWAYS" => "N",
			"PAGER_DESC_NUMBERING" => "N",
			"PAGER_SHOW_ALL" => "N",
			"PAGER_BASE_LINK_ENABLE" => "N"
		),
		false
	);?>
</div>

<?require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>