<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Фотогалерея");
?><?$APPLICATION->IncludeComponent(
	"bitrix:photogallery_user",
	"",
	Array(
		"INDEX_PAGE_TOP_ELEMENTS_COUNT" => "45",
		"SHOW_ONLY_PUBLIC" => "N",
		"PUBLIC_BY_DEFAULT" => "N",
		"MODERATE" => "N",
		"SHOW_CONTROLS_BUTTONS" => "Y",
		"USE_LIGHT_VIEW" => "Y",
		"IBLOCK_TYPE" => "",
		"IBLOCK_ID" => "",
		"GALLERY_GROUPS" => array("1"),
		"ONLY_ONE_GALLERY" => "Y",
		"MODERATION" => "N",
		"SECTION_SORT_BY" => "UF_DATE",
		"SECTION_SORT_ORD" => "DESC",
		"ELEMENT_SORT_FIELD" => "id",
		"ELEMENT_SORT_ORDER" => "desc",
		"PATH_TO_USER" => "",
		"SEF_MODE" => "N",
		"SECTION_PAGE_ELEMENTS" => "15",
		"ELEMENTS_PAGE_ELEMENTS" => "50",
		"PAGE_NAVIGATION_TEMPLATE" => "",
		"DATE_TIME_FORMAT_SECTION" => "d.m.Y",
		"DATE_TIME_FORMAT_DETAIL" => "d.m.Y",
		"GALLERY_AVATAR_SIZE" => "50",
		"ALBUM_PHOTO_THUMBS_SIZE" => "120",
		"THUMBNAIL_SIZE" => "100",
		"ORIGINAL_SIZE" => "1280",
		"JPEG_QUALITY1" => "100",
		"JPEG_QUALITY" => "100",
		"ADDITIONAL_SIGHTS" => array(),
		"USE_RATING" => "N",
		"SHOW_TAGS" => "N",
		"SET_TITLE" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_NOTES" => "",
		"SHOW_NAVIGATION" => "Y",
		"UPLOADER_TYPE" => "applet",
		"APPLET_LAYOUT" => "extended",
		"UPLOAD_MAX_FILE_SIZE" => "50",
		"USE_WATERMARK" => "Y",
		"WATERMARK_RULES" => "USER",
		"PATH_TO_FONT" => "default.ttf",
		"WATERMARK_MIN_PICTURE_SIZE" => "800",
		"USE_COMMENTS" => "N",
		"ANALIZE_SOCNET_PERMISSION" => "N",
		"VARIABLE_ALIASES" => Array(
			"USER_ID" => "USER_ID",
			"USER_ALIAS" => "USER_ALIAS",
			"SECTION_ID" => "SECTION_ID",
			"ELEMENT_ID" => "ELEMENT_ID",
			"PAGE_NAME" => "PAGE_NAME",
			"ACTION" => "ACTION"
		)
	),
false
);?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>